### ISSUE TITLE
ICMultimeter Transverter Mode

### ISSUE THREAD

**Issue by marmatBCN** [armel/ICMultiMeter#18]
Hello Armal,
Is it possible to add one digit in the transverter mode to display the frequency 10 498 770 MHz.
The second thing is, in the transverter mode, a different oscillator for Rx and Tx to display a different frequency for Tx and another for Rx.
Regards 
Marek SQ7BCN

**Comment by armel** [comment]
Hi Marek,

About your first question, this is already possible with the last version (0.1.5). 
Example...

<img width="438" alt="Capture d’écran 2022-05-12 à 13 03 08" src="https://user-images.githubusercontent.com/127889/168057150-83001a14-23aa-4e42-b662-acc927133417.png">

About your second question, maybe in a future version. I'm adding it to the todo list.

Regards,

Armel F4HWN.

**Comment by marmatBCN** [comment]
Hi Armel,
Thank you very much, great job.
 I will be following the update...

Regards,
Marek SQ7BCN

**Comment by marmatBCN** [comment]
Hi Armel,
Can the topic of a different generator multiplier for Tx and Rx be done?

**Comment by armel** [comment]
Hi Marek,

I am currently working on the ICSMeter. I would like to improve the movement of the needle. 
I would probably work again on the ICMultiMeter after. If I have time, of course. 

Regards,

Armel F4HWN

**Comment by marmatBCN** [comment]
Hi Armel,
Thanks for information,
I will follow the updates...

Regards
 Marek SQ7BCN
