### ISSUE TITLE
IC-7610 and IC-9700

### ISSUE THREAD

**Issue by g1gabyt3** [armel/ICMultiMeter#22]
Posted this as an issue because I wasn't sure how else to ask this question. Are there plans to support the IC-7610 and other Icom radios in the future? Also for radios such as the IC-9700 and the IC-7610 which both have ethernet, are there plans to support connecting straight over the M5Stack WiFi across the network for the CAT? 

I just discovered this project. I own both an IC-7610 and IC-9700. I don't have any M5Stacks so I'm fixing o order one and start experimenting. I always keep the multifunction meter up on my 7610. Being able to display that on the M5Stack would allow me to have the large waterfall or display other information. Not having to have the PC in the middle to display it would make this even better. 

de N9FC

**Comment by armel** [comment]
Hi Steven. 

Thank you for your message. 

First off all, I'm not own IC-7610 so, working on this transceiver is not very simple for me. I can't test. It's really difficult to code something without the transceiver on the front of you. About Icom radio in the future, I can't predict the future ;)

Now, note that IC-9700 is support as well as IC-7300 and IC-705. IC-9700 and IC-7300 just need a sort of Proxy, which is placed between the transceiver (linked by USB) and the M5Stack.

About connecting straight over the M5Stack WiFi across the network for the CAT, I'm not sure that it's possible. According to the IC-9700 documentation, CAT is over USB cable or Jack cable, not by Wifi. 

73 de F4HWN

**Comment by g1gabyt3** [comment]
The IC-9700 using RS-BA1 Software you can get CAT control and audio over the the network without a cable to the PC. The 7610 does the same thing. The 705 is also capable of the same thing over WiFi with the RS-BA1 software.  https://www.icomamerica.com/en/products/amateur/hf/rsba1/default.aspx

wfview is open source software that access CAT control across the network to these radios. If you are interested in the protocol since that software is open source it's code could be used as reference. https://wfview.org/

**Comment by armel** [comment]
Ok, I don't know how wfview works. I will take a look if I had time. 

But I note that wfview need a sort of proxy for using with IC-7300, as my own solution. But mine is more simple and easy to install. It's juste a simple script with less than 120 lines of code.

Now, as I said, it's hard to me to work on something what I can't test. I'm only own IC-7300 and IC-705. It will be more simple if I had an IC-9700 and IC-7610 front of me. 

73 de F4HWN

**Comment by g1gabyt3** [comment]
It should work with your 705 over WiFi. The only difference between that and the 9700 and 7610 is they would be over ethernet instead of WiFi. 

I just ordered an M5Stack. I looked through your code and don't see any reason it can't run on the 7610 over USB as is. I'll test when my M5Stack comes in to see. If I do have to change anything in the code to get it to work I'll contribute it.
