### ISSUE TITLE
Noise and powerbuttong

### ISSUE THREAD

**Issue by Thijzewijs** [armel/ICMultiMeter#26]
After using the menu, the device keeps making a noise which cannot be muted. Disabling the speaker by cutting the wires is one solution but there has to be a way to fix this by software.

Pressing the power button while powered will reboot the device, causing it to wait for the radio to connect as the device doesn't re-connect itself. Maybe hard to fix by software but annoying when pressing by accident while the radio is on your back...

**Comment by armel** [comment]
Hi,

What sort of M5Stack are you using ? BASIC, CORE2, etc. ? Your speaker problem is really strange.
And about power button, sorry but I don't think I could do anything here. 

Armel F4HWN.

**Comment by Thijzewijs** [comment]
Hello Armel,

I am using the Basic version with the Bottom2 extra large batterypack. But also without the Bottom2 this behaviour occurs after having pressed a button. Before that, it seems that there hasnt been made a sound, the amplifier or sound chip stays off. But after having made 1 sound, the noise appears. It is quite high pitched, maybe not audible for everyone?

73!

Thijs
PE1RLN 

Armel FAUVEAU ***@***.***> schreef op 14 juli 2022 20:22:37 CEST:
>Hi,
>
>What sort of M5Stack are you using ? BASIC, CORE2, etc. ? Your speaker problem is really strange.
>And about power button, sorry but I don't think I could do anything here. 
>
>Armel F4HWN.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/armel/ICMultiMeter/issues/26#issuecomment-1184762502
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Comment by armel** [comment]
Ok for the BASIC. I'll try to reproduce this strange problem. 

Armel F4HWN.

**Comment by Thijzewijs** [comment]
Ok, I tried another stack of the same type, same noise so it is unlikely a faulty unit.

Best 73!

Thijs 

Armel FAUVEAU ***@***.***> schreef op 14 juli 2022 20:45:27 CEST:
>Ok for the BASIC. I'll try to reproduce this strange problem. 
>
>Armel F4HWN.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/armel/ICMultiMeter/issues/26#issuecomment-1184781673
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.
