### ISSUE TITLE
M5stack or any module?

### ISSUE THREAD

**Issue by marmatBCN** [armel/ICMultiMeter#28]
Hi Armel,
I have M5Stack Core Basic V2.6, with 3 switches..
What module do you need to have more memory and ICSMeter run better - smoother?

**Comment by armel** [comment]
Hi,

With M5Stack Core Basic, for a smoother needle, **the only solution is use the USB mode + ICUSBProxy** (like with the IC-7300 or IC-9700). M5Stack Core Basic don't have PSRAM and Bluetooth library use too much memory. I'm sorry about that. But I've no magic solution to solve this problem 🤔

Armel de F4HWN.

**Comment by marmatBCN** [comment]
Thanks for the answer, Armel
Yes it is clear, I read it in your description ... I asked which module to buy to have more memory and the needle would run smoothly.
I need a BT connection to my ic705 is much more convenient than USB.

**Comment by armel** [comment]
Hello Marek,

Ok, sorry, so : 

- model with button version, [M5Stack FIRE](https://shop.m5stack.com/collections/m5-controllers/products/m5stack-fire-iot-development-kit-psram-v2-6?ref=LUxetaH4).
- model with touch screen version, [M5Stack CORE2](https://shop.m5stack.com/collections/m5-controllers/products/m5stack-core2-esp32-iot-development-kit?ref=LUxetaH4) or [M5Stack AWS](https://shop.m5stack.com/collections/m5-controllers/products/m5stack-core2-esp32-iot-development-kit-for-aws-iot-edukit?ref=LUxetaH4).

With these models (which embed PSRAM) you will have a smooth needle **with BT connection**.

Don't forget that, with the coupon code **F4HWN**, you can get a 5% discount on the official M5Stack shop.

Armel de F4HWN

**Comment by marmatBCN** [comment]
Hello Armel,
Thank you for your response,
I ordered a version  [M5Stack CORE2] with touch buttons ,
I didn't know that this module comes with PSRAM as standard....
Thanks for coupon code

Marek SQ7BCN

**Comment by armel** [comment]
Hello Marek,

Don't worry.
All M5Stack CORE2 with touch buttons have 8Mb of PSRAM in standard 👍🏻
Last, but not least, I'm working to improve BT support and increase BT speed. May be a new version in few days. 

Armel de F4HWN

**Comment by marmatBCN** [comment]
Hello Armel,

This is very good news.
You did not think to change - to facilitate the operation of the voice keyer, for the version with Touch LCD to make a screen with 8 buttons?

Marek SQ7BCN

**Comment by armel** [comment]
Hi Marek,

My next project will be an ICKeyer and will work only on M5Stack CORE2 or AWS, with Touch LCD 🤗 
Quick demo (still in development) : https://www.youtube.com/watch?v=L0ZOretqC1w

Armel de F4HWN
