### ISSUE TITLE
ICOM 9700 Testing

### ISSUE THREAD

**Issue by tomvdb** [armel/ICMultiMeter#5]
Hi Armel, 

I moved our conversation to an github issue instead of tweeting you every time :p

So the first issue I had, where the m5stack was crashing was my own fault. I set the address as 2A instead of A2. Once that was corrected it started showing information, but the info was still incorrect, but no more crashes.

Further investigation showed that my icom is returning a double response and you are expecting a single response. 

For example:

The civ command sent for getting the frequency:

`['/?civ', 'fe,fe,a2,e0,03,fd,115900,COM10']`

gives the following response:

`fefea2e003fdfefee0a2030050864401`

Its parsing that incorrectly on the esp32 side because of the extra response. By modifying the response in ICUSBProxy (ie, removing the first response):

`        response = response[12:]`

the display is now showing partly correct information, albeit very slow updates. It takes about 5-10 seconds before it updates after I made changes on the radio (this could also be because of the debug messages, I will test).

Other issues I see is that it shows P.Amp enabled, but its not, the tx also doesn't light up when doing a tx

I'll play some more and give you more details, but this is what I found this morning so far

Great project!

T

**Comment by armel** [comment]
Hi Tom,

Hummm, I Think of something : there is a double VFO on IC-9700 ? Right ?
I wonder if that's where the problems come from. 

Armel.

**Comment by tomvdb** [comment]
Hi Armel, it does indeed have a double vfo, not sure if it makes a difference whether both is activated or not. I did my tests with just one active

T

**Comment by armel** [comment]
Hi Tom, what about your CI-V settings on your TX ?
Mine is :

```
Connectors > CI-V > CI-V USB Port       Unlink from [REMOTE]
Connectors > CI-V > CI-V USB Baud Rate  115200
Connectors > CI-V > CI-V USB Echo Back  OFF
```

All seems to work, on IC-7300 and IC-9700

https://twitter.com/ManuelLausmann/status/1516899830299299842

Armel.
