### ISSUE TITLE
Feature Request - M5 Stack - Fire

### ISSUE THREAD

**Issue by tomvdb** [armel/ICMultiMeter#6]
I would like to request M5 Stack - Fire support if its possible

https://shop.m5stack.com/products/fire-iot-development-kit?variant=16804798169178

73

**Comment by armel** [comment]
Hi Tom,

About M5 Stack - Fire, it works too. 
You need to select BASIC (or GREY) BOARD.
The only trap, for this model, is to precisely target the upload port in plateformio.ini.
So in [env:m5stack-basic-grey] section, I add this simple line,

upload_port = /dev/cu.wchusbserial52D20510211

Of course, this port is certainly different for you (I'm on MacOS).

Armel.

**Comment by tomvdb** [comment]
Cool, I'll give it a shot.

T
