### ISSUE TITLE
Icom 9700 (Possible Icom 7300) Direct Connection idea

### ISSUE THREAD

**Issue by tomvdb** [armel/ICMultiMeter#7]
The Icom 9700 ci-v has a 3.5mm jack connection that can be used to send and receive ci-v commands. Could make a neat direct connection between m5 stack and IC MultiMeter with IC Multimeter sending those commands via serial port.

Just an idea I had ;)

Thanks for the great project!

**Comment by armel** [comment]
Hi Tom,

Yes, this is the same on 7300. But I haven't got this sort of cable (USB to 3.5mm Jack).
Code will be the same, I think.

Armel.

**Comment by tomvdb** [comment]
I'll do some tests and get back to you

T

**Comment by df3fx** [comment]
Hi,
I think there might be some misunderstanding. The CI-V port of 7300 and 9700 ( and other Icom trx) is purely a classic serial  one with combined rx and tx lines. So nothing to do with/ no need for USB . 
Would be very useful to have a connection possibility via that port which is usually free or easily "multipliable". 
Interfacing with the 3.5mm ci-v port could be easily done via the pins of the M5 stack i think. 

Best 73

Felix
